const ACTIONS = {
    LOGIN: 'LOGIN',
    GET_TOKEN: 'GET_TOKEN',
    GET_USER: 'GET_USER',
    GET_ALL_USERS: 'GET_ALL_USERS',
    SEND_DETAILS: 'SEND_DETAILS',
    FORM_SEND_SUCCESS: 'FORM_SEND_SUCCESS',
    FORM_SEND_FAILURE: 'FORM_SEND_FAILURE'
}

export default ACTIONS